### ISSUE TITLE
Cannot destructure property 'totalEnergy'

### ISSUE THREAD

**Issue by KSYMEK** [LokiSharp/ScreepsScript#1]
Hi, I wanted to see how you AI works, but after startup this error occures:

`TypeError: Cannot destructure property `totalEnergy` of 'undefined' or 'null'.
    at ControllerExtension.drawEnergyHarvestInfo  (../src/mount/StructureExtension/ControllerExtension/ControllerExtension.ts:42:43)
    at ControllerExtension.onWork  (../src/mount/StructureExtension/ControllerExtension/ControllerExtension.ts:18:9)
    at App.errorMapper [as _catcher]  (../src/utils/global/ErrorMapper.ts:82:4)
    at App.doWithCatcher  (../src/modules/framework/index.ts:205:9)
    at allItem.forEach.item  (../src/modules/framework/index.ts:195:65)
    at App.do  (../src/modules/framework/index.ts:195:14)
    at App.run  (../src/modules/framework/index.ts:142:12)
    at Object.loop  (../src/main.ts:40:6)`

**Comment by KSYMEK** [comment]
But on my localhost server all works fine

**Comment by LokiSharp** [comment]
I guess you might set the first spawn before push code. So it not trigger AppLifecycleCallback born
https://github.com/LokiSharp/ScreepsScript/blob/aa6fe4d5bca18866cee87d83e0bf69f1db3780ee/src/mount/index.ts#L87-L97

You can use `[RoomName].controller.stateScanner()` to init Memory.stats

**Comment by KSYMEK** [comment]
Ohh I see you are absolutly correct thank you, I hope to push some changes. This AI has big potential
