### ISSUE TITLE
shardSeason]ErrorMapper -> sourceMappedStackTrace -> outStack TypeError: this.memory.find is not a function

### ISSUE THREAD

**Issue by 923132714** [LokiSharp/ScreepsScript#4]
```
[上午10:52:54][shardSeason]ErrorMapper -> sourceMappedStackTrace -> outStack TypeError: this.memory.find is not a function
[上午10:52:54][shardSeason]TypeError: this.memory.find is not a function
    at RoomPowerController.hasTask  (../src/modules/room/power/controller.ts:174:25)
    at RoomPowerController.addTask  (../src/modules/room/power/controller.ts:40:16)
    at RoomSpawnController.runSpawn  (../src/modules/room/spawn/index.ts:117:26)
    at SpawnExtension.onWork  (../src/mount/StructureExtension/SpawnExtension/SpawnExtension.ts:9:22)
    at App.errorMapper [as _catcher]  (../src/utils/global/ErrorMapper.ts:82:4)
    at App.doWithCatcher  (../src/modules/framework/index.ts:205:9)
    at allItem.forEach.item  (../src/modules/framework/index.ts:195:65)
    at App.do  (../src/modules/framework/index.ts:195:14)
    at App.run  (../src/modules/framework/index.ts:142:12)
```
season 应用 88b8287 次提交后出现问题

**Comment by LokiSharp** [comment]
这个 commit 把 room.memory 里老的 power 和 powerTasks 字段废弃了，需要手动删除，你试试看是不是这个问题

**Comment by 923132714** [comment]
ok 问题解决
