### ISSUE TITLE
新房 TypeError: Cannot destructure property `totalEnergy` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by 923132714** [LokiSharp/ScreepsScript#8]
```shell
[下午9:16:59][shardSeason]TypeError: Cannot destructure property `totalEnergy` of 'undefined' or 'null'.
    at ControllerExtension.drawEnergyHarvestInfo  (../src/mount/StructureExtension/ControllerExtension/ControllerExtension.ts:41:43)
    at ControllerExtension.onWork  (../src/mount/StructureExtension/ControllerExtension/ControllerExtension.ts:17:9)
    at App.errorMapper [as _catcher]  (../src/utils/global/ErrorMapper.ts:82:4)
    at App.doWithCatcher  (../src/modules/framework/index.ts:205:9)
    at allItem.forEach.item  (../src/modules/framework/index.ts:195:65)
    at App.do  (../src/modules/framework/index.ts:195:14)
    at App.run  (../src/modules/framework/index.ts:142:12)
    at Object.loop  (../src/main.ts:40:6)
```

**Comment by 923132714** [comment]
未初始化room统计数据
